apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-istio-mc
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    # helm:
    #   version: v3
    #   valueFiles:
    #   - values-bwb-{{ .Values.env }}.yaml  
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://192.168.99.172:31049'
        - name: AVP_AUTH_TYPE
          value: k8s
        - name: HELM_VALUES
          value: |
            ca-cert.pem:
              username: <path:kv/data/mysql#user>                        
    path: .  
    repoURL: https://github.com/paas2/istio.git
    targetRevision: HEAD
  project: istio