apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: helm-istio-remote-secret
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: istio
  
  source:
    helm:
      version: v3
      valueFiles:
      - values-{{ .Values.env }}.yaml
    path: helm-charts/clusters/bwb
    repoURL: https://github.com/paas2/istio.git
    targetRevision: HEAD
    
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true 

