apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mc
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    plugin:
      name: argocd-vault-plugin                   
    path: mc-init  
    repoURL: https://github.com/paas2/istio.git
    targetRevision: HEAD
  project: istio