apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cacerts
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    plugin:
      name: argocd-vault-plugin-helm  
      env:
        - name: HELM_VALUES
          value: |
            certsPath: bwb-dev                     
    path: .
    repoURL: https://github.com/paas2/istio-mc-trust.git
    targetRevision: HEAD
  project: istio