apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mc
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_K8S_ROLE
          value: vplugin
        - name: AVP_TYPE
          value: vault
        - name: AVP_VAULT_ADDR
          value: 'http://192.168.99.172:31049'
        - name: AVP_AUTH_TYPE
          value: k8s                      
    path: mc-init  
    repoURL: https://github.com/paas2/istio.git
    targetRevision: HEAD
  project: istio