apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-remote-secret
spec:
  project: istio

  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'

  source:
    plugin:
      name: argocd-vault-plugin-helm  
      env:
        - name: HELM_VALUES
          value: |
            global:   
              env: dev
              clusterName: bwb                  
    path: helm-charts/clusters/operator/bwb
    repoURL: https://github.com/paas2/istio.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true   